version: "3.8"

services:
  mongo:
    image: mongo
    ports: 
    - 27017:27017
    environment:
      MONGO_INITDB_ROOT-USERNAME: raj
      MONGO_INITDB_ROOT-PASSWORD: raj


  mongo-express:   
    image: mongo-express
    ports: 
    - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: raj
      ME_CONFIG_MONGODB_ADMINPASSWORD: raj
      ME_CONFIG_MONGODB_AUTH_DATABASE: admin
      ME_CONFIG_MONGODB_URL: "mongodb://raj:raj@localhost:27017/?authSource=admin"


